/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import BD.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omar0
 */
public class GestionarMobiliario extends javax.swing.JFrame {

    /**
     * Creates new form GestionarMobiliario
     */
    public GestionarMobiliario() {
        initComponents();
    }
    Conexion baseDatos = new Conexion().conectar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextsillas = new javax.swing.JTextField();
        jTextmesas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerSillaA = new javax.swing.JSpinner();
        jSpinnerSillaB = new javax.swing.JSpinner();
        jSpinnerMesaA = new javax.swing.JSpinner();
        jSpinnerMesaB = new javax.swing.JSpinner();
        jButtonAgregar = new javax.swing.JToggleButton();
        jButtonBaja = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Gestionar Rentas");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Gestionar Mobiliario");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total de sillas:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Total de mesas:");

        jTextsillas.setEditable(false);
        try {
            // TODO add your handling code here:
            int noSillas = 0;

            ResultSet resultado = baseDatos.consultar("SELECT * FROM MOBILARIO_TABLA ");

            if (resultado.next()) {
                noSillas = resultado.getInt("mobilario_cantidad_sillas");

                String sillas = noSillas + "";

                jTextsillas.setText(sillas);

            } else {
                jTextsillas.setText("0");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionarMobiliario.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTextmesas.setEditable(false);
        try {
            // TODO add your handling code here:

            int noMesas = 0;
            ResultSet resultado = baseDatos.consultar("SELECT * FROM MOBILARIO_TABLA ");

            if (resultado.next()) {

                noMesas = resultado.getInt("mobilario_cantidad_mesas");

                String mesas = noMesas + "";

                jTextmesas.setText(mesas);

            } else {
                jTextmesas.setText("0");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionarMobiliario.class.getName()).log(Level.SEVERE, null, ex);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Dar de alta");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Dar de baja");

        jSpinnerSillaA .setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinnerSillaA .setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerSillaA .setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSpinnerSillaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinnerSillaB .setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerSillaB .setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSpinnerMesaA .setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinnerMesaA .setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerMesaA .setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSpinnerMesaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinnerMesaB.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerMesaB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonBaja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBaja.setText("Baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Sillas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Sillas");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Mesas");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Mesas");

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerSillaA, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jSpinnerMesaA)))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAgregar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jTextsillas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabel2))))
                        .addGap(138, 138, 138)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerMesaB)
                                    .addComponent(jSpinnerSillaB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jTextmesas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jButtonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextsillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextmesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel8)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jSpinnerSillaB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerMesaB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addGap(48, 48, 48))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jSpinnerSillaA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jSpinnerMesaA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAgregar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jButtonGenerarMobiliarioActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        try {
            // TODO add your handling code here:
            int noSillas = 0;
            int noMesas = 0;
            ResultSet resultado = baseDatos.consultar("SELECT * FROM MOBILARIO_TABLA ");

            if (resultado.next()) {
                noSillas = resultado.getInt("mobilario_cantidad_sillas");
                noMesas = resultado.getInt("mobilario_cantidad_mesas");

                String sillas = noSillas + "";
                String mesas = noMesas + "";

                jTextsillas.setText(sillas);
                jTextmesas.setText(mesas);

                JOptionPane.showMessageDialog(null, "Mobilario actualizado", null, JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "No hay mobiliario registrado", null, JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionarMobiliario.class.getName()).log(Level.SEVERE, null, ex);
        }


    }         
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:

        int mesas = 0;
        mesas = (int) jSpinnerMesaA.getValue();

        int sillas = 0;
        sillas = (int) jSpinnerSillaA.getValue();

        if (sillas != 0 || mesas != 0  ) {

            if (sillas == 0) {

                String jTextMesas = jTextmesas.getText();
                int mesasTal = Integer.parseInt(jTextMesas) + mesas;

                boolean sentencia;
                sentencia = baseDatos.ejecutar("UPDATE mobilario_tabla SET mobilario_cantidad_mesas = '" + mesasTal + "' WHERE folio_mobilario = 001");

                if (sentencia == true) {
                    JOptionPane.showMessageDialog(null, "Se registro correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar ");
                }
            } else if (mesas == 0) {

                String jTextSillas = jTextsillas.getText();
                int sillasTal = Integer.parseInt(jTextSillas) + sillas;

                boolean sentencia;
                sentencia = baseDatos.ejecutar("UPDATE mobilario_tabla SET mobilario_cantidad_sillas = '" + sillasTal + "' WHERE folio_mobilario = 001");

                if (sentencia == true) {
                    JOptionPane.showMessageDialog(null, "Se registro correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar ");
                }

            } else {

                String jTextMesas = jTextmesas.getText();
                int mesasTal = Integer.parseInt(jTextMesas) + mesas;

                String jTextSillas = jTextsillas.getText();
                int sillasTal = Integer.parseInt(jTextSillas) + sillas;

                boolean sentencia;
                sentencia = baseDatos.ejecutar("UPDATE mobilario_tabla SET mobilario_cantidad_mesas = '" + mesasTal + "' , mobilario_cantidad_sillas = '" + sillasTal + "'  WHERE folio_mobilario = 001");

                if (sentencia == true) {
                    JOptionPane.showMessageDialog(null, "Se registro correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar ");

                }
            }

        } else {

            JOptionPane.showMessageDialog(null, "Ingresa la cantidad de sillas o mesas a registrar");
        }

        jSpinnerMesaA.setValue(0);
        jSpinnerSillaA.setValue(0);
        jButtonGenerarMobiliarioActionPerformed(evt);

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // TODO add your handling code here:
        int mesas = 0;
        mesas = (int) jSpinnerMesaB.getValue();

        int sillas = 0;
        sillas = (int) jSpinnerSillaB.getValue();

        if (sillas != 0 || mesas != 0) {

            if (sillas == 0) {

                String jTextMesas = jTextmesas.getText();
                int mesasTal = Integer.parseInt(jTextMesas) - mesas;

                if (mesasTal < 0) {
                      JOptionPane.showMessageDialog(null, "No se pueden borar  " + mesas+ " mesas  " + "existen " + jTextMesas + " mesas" );
                }else{
                    
                

                boolean sentencia;
                sentencia = baseDatos.ejecutar("UPDATE mobilario_tabla SET mobilario_cantidad_mesas = '" + mesasTal + "' WHERE folio_mobilario = 001");

                if (sentencia == true) {
                    JOptionPane.showMessageDialog(null, "Se borro correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo borrar");
                }
            }
            } else if (mesas == 0) {

                String jTextSillas = jTextsillas.getText();
                int sillasTal = Integer.parseInt(jTextSillas) - sillas;
                
                if (sillasTal < 0) {
                      JOptionPane.showMessageDialog(null, "No se pueden borar " + sillas+ " sillas, " + "existen " + jTextSillas + "sillas" );
                }else{

                boolean sentencia;
                sentencia = baseDatos.ejecutar("UPDATE mobilario_tabla SET mobilario_cantidad_sillas = '" + sillasTal + "' WHERE folio_mobilario = 001");

                if (sentencia == true) {
                    JOptionPane.showMessageDialog(null, "Se borro correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo borrar ");
                }
                }
            } else {

                String jTextMesas = jTextmesas.getText();
                int mesasTal = Integer.parseInt(jTextMesas) - mesas;

                String jTextSillas = jTextsillas.getText();
                int sillasTal = Integer.parseInt(jTextSillas) - sillas;
                
                if (mesasTal < 0 || sillasTal < 0) {
                     JOptionPane.showMessageDialog(null, "No se pudo borrar; verifica la cantidad a borrar ");
                }else{
                    
                

                boolean sentencia;
                sentencia = baseDatos.ejecutar("UPDATE mobilario_tabla SET mobilario_cantidad_mesas = '" + mesasTal + "' , mobilario_cantidad_sillas = '" + sillasTal + "'  WHERE folio_mobilario = 001");

                if (sentencia == true) {
                    JOptionPane.showMessageDialog(null, "Se borro correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo borrar ");

                }
            }
            }

        } else {

            JOptionPane.showMessageDialog(null, "Ingresa la cantidad de sillas o mesas a borrar");
        }

        jSpinnerMesaB.setValue(0);
        jSpinnerSillaB.setValue(0);
        jButtonGenerarMobiliarioActionPerformed(evt);


    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
         // TODO add your handling code here:
         
         
        MenuPrincipal gest= new MenuPrincipal();
        gest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarMobiliario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonAgregar;
    private javax.swing.JToggleButton jButtonBaja;
    private javax.swing.JToggleButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerMesaA;
    private javax.swing.JSpinner jSpinnerMesaB;
    private javax.swing.JSpinner jSpinnerSillaA;
    private javax.swing.JSpinner jSpinnerSillaB;
    private javax.swing.JTextField jTextmesas;
    private javax.swing.JTextField jTextsillas;
    // End of variables declaration//GEN-END:variables
}
